### ISSUE TITLE
Migration error on column stages.comment_on_zendesk_tickets with pgsql

### ISSUE THREAD

**Issue by ryan0x44** [zendesk/samson#1820]
When running migrations against a fresh postgres database I get the following error with `db/migrate/20160901175936_prevent_3_state_booleans.rb`:

```
Migrating to Prevent3StateBooleans (20160901175936)
== 20160901175936 Prevent3StateBooleans: migrating ============================
-- change_column_default(:stages, :update_github_pull_requests, false)
   -> 0.0296s
-- change_column_null(:stages, :update_github_pull_requests, false)
   -> 0.0021s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column stages.comment_on_zendesk_tickets does not exist
LINE 1: ...ges" SET "comment_on_zendesk_tickets" = 'f' WHERE "stages"."...
                                                             ^
: UPDATE "stages" SET "comment_on_zendesk_tickets" = 'f' WHERE "stages"."comment_on_zendesk_tickets" IS NULL
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/usr/local/bundle/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:116:in `exec_delete'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:133:in `update'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `update'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/relation.rb:395:in `update_all'
/app/db/migrate/20160901175936_prevent_3_state_booleans.rb:10:in `block in up'
/app/db/migrate/20160901175936_prevent_3_state_booleans.rb:9:in `each'
/app/db/migrate/20160901175936_prevent_3_state_booleans.rb:9:in `up'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:792:in `exec_migration'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:772:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:771:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:951:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1212:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1280:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/transactions.rb:211:in `transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1280:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1211:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1184:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1183:in `each'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1183:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1132:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1299:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1132:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1006:in `up'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:984:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/airbrake-5.7.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column stages.comment_on_zendesk_tickets does not exist
LINE 1: ...ges" SET "comment_on_zendesk_tickets" = 'f' WHERE "stages"."...
                                                             ^
: UPDATE "stages" SET "comment_on_zendesk_tickets" = 'f' WHERE "stages"."comment_on_zendesk_tickets" IS NULL
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/usr/local/bundle/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:116:in `exec_delete'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:133:in `update'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `update'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/relation.rb:395:in `update_all'
/app/db/migrate/20160901175936_prevent_3_state_booleans.rb:10:in `block in up'
/app/db/migrate/20160901175936_prevent_3_state_booleans.rb:9:in `each'
/app/db/migrate/20160901175936_prevent_3_state_booleans.rb:9:in `up'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:792:in `exec_migration'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:772:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:771:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:951:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1212:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1280:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/transactions.rb:211:in `transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1280:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1211:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1184:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1183:in `each'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1183:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1132:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1299:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1132:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1006:in `up'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:984:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/airbrake-5.7.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
PG::UndefinedColumn: ERROR:  column stages.comment_on_zendesk_tickets does not exist
LINE 1: ...ges" SET "comment_on_zendesk_tickets" = 'f' WHERE "stages"."...
                                                             ^
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/usr/local/bundle/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:116:in `exec_delete'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:133:in `update'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `update'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/relation.rb:395:in `update_all'
/app/db/migrate/20160901175936_prevent_3_state_booleans.rb:10:in `block in up'
/app/db/migrate/20160901175936_prevent_3_state_booleans.rb:9:in `each'
/app/db/migrate/20160901175936_prevent_3_state_booleans.rb:9:in `up'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:792:in `exec_migration'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:773:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:772:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `with_connection'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:771:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:951:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1212:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1280:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/transactions.rb:211:in `transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1280:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1211:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1184:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1183:in `each'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1183:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1132:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1299:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1132:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:1006:in `up'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/migration.rb:984:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/usr/local/bundle/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/airbrake-5.7.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
/app/config/initializers/airbrake.rb:37:in `notify': undefined method `env' for Airbrake::Rails:Module (NoMethodError)
	from /app/config/initializers/airbrake.rb:46:in `notify_sync'
	from /usr/local/bundle/gems/airbrake-5.7.1/lib/airbrake.rb:76:in `block in <top (required)>'
```

I'm using Docker image v1413

**Comment by grosser** [comment]
yeah that column change belongs into the zendesk plugin ... fix coming
