### ISSUE TITLE
Gemfile missing dependencies + Cannot load app in production mode

### ISSUE THREAD

**Issue by vitxd** [zendesk/samson#2100]
Hello everyone,
I've tried to install your cool tool and I've found some problems along the way so I thought my experience might help you.
Let's start saying that I don't know anything about Ruby or Rails. I've basically learnt a very tiny bit while trying to start up samson :).

First of all I think you missed 2 dependencies in your Gemfile. Off the shelf, running bundle install it will break but with them in it it runs alright. The gems missing are execjs and therubyracer.

Also it would be nice to add the fact that before installing anything, some libraries are needed.. a simple 
```
$ apt-get install -y libmysqlclient-dev  ruby-pg libpq-dev
```

will fix everything.

Other issue I've encountered is that I could not start the application at all in production mode. The process starts alright but when I try to land on the page, it shows an error message saying to check the logs and in the logs I found this:

```
Started GET "/login?redirect_to=%2F" for 10.0.0.12 at 2017-06-22 11:22:31 +0000
Processing by SessionsController#new as HTML
  Parameters: {"redirect_to"=>"/"}
  Rendering sessions/new.html.erb within layouts/application
  Rendered sessions/new.html.erb within layouts/application (2.6ms)
Completed 500 Internal Server Error in 14ms (ActiveRecord: 0.0ms)
  
ArgumentError (wrong number of arguments (given 1, expected 2)):
  
airbrake-ruby (2.2.0) lib/airbrake-ruby/notifier.rb:174:in `build_notice'
airbrake (6.0.0) lib/airbrake/rack/middleware.rb:68:in `notify_airbrake'
airbrake-user_informer (0.2.0) lib/airbrake/user_informer.rb:7:in `notify_airbrake'
airbrake (6.0.0) lib/airbrake/rack/middleware.rb:54:in `rescue in call'
airbrake (6.0.0) lib/airbrake/rack/middleware.rb:51:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
railties (5.1.0) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/request_id.rb:25:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
airbrake-user_informer (0.2.0) lib/airbrake/user_informer.rb:26:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
activesupport (5.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/static.rb:125:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
railties (5.1.0) lib/rails/engine.rb:522:in `call'
newrelic_rpm (4.1.0.333) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
puma (3.8.2) lib/puma/configuration.rb:224:in `call'
puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
puma (3.8.2) lib/puma/server.rb:435:in `process_client'
puma (3.8.2) lib/puma/server.rb:299:in `block in run'
puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
AIRBRAKE: SystemExit - exit - /home/samson/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/server.rb:292:in `exit'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rack-2.0.1/lib/rack/server.rb:292:in `block in start'
/home/samson/.rvm/gems/ruby-2.3.3/gems/puma-3.8.2/lib/puma/single.rb:106:in `join'
/home/samson/.rvm/gems/ruby-2.3.3/gems/puma-3.8.2/lib/puma/single.rb:106:in `run'
/home/samson/.rvm/gems/ruby-2.3.3/gems/puma-3.8.2/lib/puma/launcher.rb:172:in `run'
/home/samson/.rvm/gems/ruby-2.3.3/gems/puma-3.8.2/lib/rack/handler/puma.rb:64:in `run'
```

Thank you very much for any support!

Vittorio

**Comment by grosser** [comment]
thx for the report, new user perspective is always helpful :)

can you bundle now when 'execjs/therubyracer' gems are removed again ?
... might need a nodejs install to work without them ...

adding install instructions for all OS is a bit out of the scope, but I guess seeing how it is done with apt gives a hint of what might be breaking ...

fixed airbrake issue here https://github.com/zendesk/samson/pull/2101

**Comment by vitxd** [comment]
still erroring, different error now:

```
Started GET "/login?redirect_to=%2F" for 12.0.0.12 at 2017-06-22 13:14:05 +0000
Processing by SessionsController#new as HTML
  Parameters: {"redirect_to"=>"/"}
  Rendering sessions/new.html.erb within layouts/application
  Rendered sessions/new.html.erb within layouts/application (1.2ms)
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms)
  
ActionView::Template::Error (The asset "github.png" is not present in the asset pipeline.):
    11:       <% ['Github', 'Google', 'LDAP', 'Gitlab'].each do |provider| %>
    12:         <% if Rails.application.config.samson.auth.public_send(provider.downcase) %>
    13:           <%= link_to omniauth_path(provider.downcase.to_sym), class: "action #{provider.downcase}" do %>
    14:             <%= image_tag image_url("#{provider.downcase}.png") %> Login with <%= provider %>
    15:           <% end %>
    16:         <% end %>
    17:       <% end %>
  
app/views/sessions/new.html.erb:14:in `block (2 levels) in _app_views_sessions_new_html_erb___3104551618206628066_13696040'
app/views/sessions/new.html.erb:13:in `block in _app_views_sessions_new_html_erb___3104551618206628066_13696040'
app/views/sessions/new.html.erb:11:in `each'
app/views/sessions/new.html.erb:11:in `_app_views_sessions_new_html_erb___3104551618206628066_13696040'
```

**Comment by grosser** [comment]
dev or prod ?

... if it's prod then it's missing `rake assets:precompile`

**Comment by vitxd** [comment]
production and running your command is still moaning about `execjs/ngannotate-rails`

**Comment by vitxd** [comment]
btw, thank you very much for the prompt response!

**Comment by grosser** [comment]
hmm that should have fixed it ... did you restart the server too ?

maybe this helps:
`RAILS_ENV=production PRECOMPILE=1 PLUGINS=all bundle exec rake assets:precompile assets:clean[0] --trace`

**Comment by vitxd** [comment]
same error, I will paste the trace:

```
samson@jenkins:/opt/samson$ RAILS_ENV=production PRECOMPILE=1 PLUGINS=all bundle exec rake assets:precompile assets:clean[0] --trace
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'ngannotate-rails'.
Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
Backtrace for gem load error is:
/home/samson/.rvm/gems/ruby-2.3.3/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
/home/samson/.rvm/gems/ruby-2.3.3/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/ngannotate-rails-1.2.2/lib/ngannotate/processor3.rb:1:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/ngannotate-rails-1.2.2/lib/ngannotate/rails/railtie.rb:5:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/ngannotate-rails-1.2.2/lib/ngannotate/rails.rb:2:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/ngannotate-rails-1.2.2/lib/ngannotate.rb:8:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/ngannotate-rails-1.2.2/lib/ngannotate-rails.rb:1:in `require_relative'
/home/samson/.rvm/gems/ruby-2.3.3/gems/ngannotate-rails-1.2.2/lib/ngannotate-rails.rb:1:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `each'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `block in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `each'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler.rb:108:in `require'
/opt/samson/config/application.rb:11:in `<top (required)>'
/opt/samson/Rakefile:8:in `require_relative'
/opt/samson/Rakefile:8:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/bin/rake:22:in `load'
/home/samson/.rvm/gems/ruby-2.3.3/bin/rake:22:in `<main>'
/home/samson/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/home/samson/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Bundler Error Backtrace:
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `each'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `block in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `each'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler.rb:108:in `require'
/opt/samson/config/application.rb:11:in `<top (required)>'
/opt/samson/Rakefile:8:in `require_relative'
/opt/samson/Rakefile:8:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/bin/rake:22:in `load'
/home/samson/.rvm/gems/ruby-2.3.3/bin/rake:22:in `<main>'
/home/samson/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/home/samson/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
/home/samson/.rvm/gems/ruby-2.3.3/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
/home/samson/.rvm/gems/ruby-2.3.3/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/ngannotate-rails-1.2.2/lib/ngannotate/processor3.rb:1:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/ngannotate-rails-1.2.2/lib/ngannotate/rails/railtie.rb:5:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/ngannotate-rails-1.2.2/lib/ngannotate/rails.rb:2:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/samson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/ngannotate-rails-1.2.2/lib/ngannotate.rb:8:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/ngannotate-rails-1.2.2/lib/ngannotate-rails.rb:1:in `require_relative'
/home/samson/.rvm/gems/ruby-2.3.3/gems/ngannotate-rails-1.2.2/lib/ngannotate-rails.rb:1:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `each'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `block in require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `each'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `require'
/home/samson/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.1/lib/bundler.rb:108:in `require'
/opt/samson/config/application.rb:11:in `<top (required)>'
/opt/samson/Rakefile:8:in `require_relative'
/opt/samson/Rakefile:8:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/samson/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/samson/.rvm/gems/ruby-2.3.3/bin/rake:22:in `load'
/home/samson/.rvm/gems/ruby-2.3.3/bin/rake:22:in `<main>'
/home/samson/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/home/samson/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by vitxd** [comment]
is it worth starting from scratch?

**Comment by vitxd** [comment]
I can confirm that adding the 2 gem dependencies back on Gemfile and running bundle install fix the precompile command and the app can start in production mode.

**Comment by vitxd** [comment]
I have another problem with permission but I probably should create a new ticket :)

**Comment by grosser** [comment]
Is nodejs installed on the host ?
... Never had to install these extra gems 😑

**Comment by vitxd** [comment]
Exactly, I don't have nodejs installed on the host. I don't think the documentation says it is required :smile:

**Comment by grosser** [comment]
new docs says to install it ... so we are done here ? :D

**Comment by vitxd** [comment]
I can confirm that with nodejs installed everything runs smoothly. Thanks very much for the support!

**Comment by grosser** [comment]
glad that worked out :D
keep spamming issues, always hard to get onboarding right :)
