### ISSUE TITLE
Running db:migrate on empty mysql db fails

### ISSUE THREAD

**Issue by viraptor** [zendesk/samson#2682]
Using an initial checkout of samson v2218, I'm trying to run the db:migrate on a mysql database.

Migration file `db/migrate/20171101121933_remove_kubernetes_job.rb` fails with:
```
== 20171101121933 RemoveKubernetesJob: migrating ==============================
-- remove_column(:builds, :kubernetes_job, :boolean, {:default=>false, :null=>false})
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Can't DROP 'kubernetes_job'; check that column/key exists: ALTER TABLE `builds` DROP `kubernetes_job`
/Users/viraptor/Projects/samson/lib/samson/mapped_database_exceptions.rb:9:in `execute'
/Users/viraptor/Projects/samson/db/migrate/20171101121933_remove_kubernetes_job.rb:4:in `change'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Can't DROP 'kubernetes_job'; check that column/key exists: ALTER TABLE `builds` DROP `kubernetes_job`
/Users/viraptor/Projects/samson/lib/samson/mapped_database_exceptions.rb:9:in `execute'
/Users/viraptor/Projects/samson/db/migrate/20171101121933_remove_kubernetes_job.rb:4:in `change'

Caused by:
Mysql2::Error: Can't DROP 'kubernetes_job'; check that column/key exists
/Users/viraptor/Projects/samson/lib/samson/mapped_database_exceptions.rb:9:in `execute'
/Users/viraptor/Projects/samson/db/migrate/20171101121933_remove_kubernetes_job.rb:4:in `change'
Tasks: TOP => db:migrate
```

Ruby: 2.5.0
environment: MacOS 10.13

**Comment by viraptor** [comment]
User error: `db:migrate` doesn't work with `PLUGINS=''`.

**Comment by grosser** [comment]
it is supposed to work with `PLUGINS=''`

**Comment by grosser** [comment]
caused by this guy again https://github.com/zendesk/samson/pull/2356 :trollface:
