### ISSUE TITLE
Bootsnap issue breaks app initialisation

### ISSUE THREAD

**Issue by viraptor** [zendesk/samson#2683]
Running any rake task like:
```
RAILS_ENV=test DATABASE_URL=mysql2://root@127.0.0.1/samson_test bundle exec rake db:migrate
```
causes the following failure, which is likely to come from the use of bootsnap:
```
/opt/boxen/rbenv/versions/2.5.0/lib/ruby/2.5.0/set.rb:625: warning: already initialized constant Set::InspectKey
/opt/rubies/2.5.0/lib/ruby/2.5.0/set.rb:625: warning: previous definition of InspectKey was here
/opt/boxen/rbenv/versions/2.5.0/lib/ruby/2.5.0/pathname.rb:20: warning: already initialized constant Pathname::TO_PATH
/opt/rubies/2.5.0/lib/ruby/2.5.0/pathname.rb:20: warning: previous definition of TO_PATH was here
/opt/boxen/rbenv/versions/2.5.0/lib/ruby/2.5.0/pathname.rb:22: warning: already initialized constant Pathname::SAME_PATHS
/opt/rubies/2.5.0/lib/ruby/2.5.0/pathname.rb:22: warning: previous definition of SAME_PATHS was here
/opt/boxen/rbenv/versions/2.5.0/lib/ruby/2.5.0/pathname.rb:34: warning: already initialized constant Pathname::SEPARATOR_LIST
/opt/rubies/2.5.0/lib/ruby/2.5.0/pathname.rb:34: warning: previous definition of SEPARATOR_LIST was here
/opt/boxen/rbenv/versions/2.5.0/lib/ruby/2.5.0/pathname.rb:35: warning: already initialized constant Pathname::SEPARATOR_PAT
/opt/rubies/2.5.0/lib/ruby/2.5.0/pathname.rb:35: warning: previous definition of SEPARATOR_PAT was here
/opt/boxen/rbenv/versions/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/rbconfig.rb:16: warning: already initialized constant RbConfig::TOPDIR
/opt/rubies/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/rbconfig.rb:16: warning: previous definition of TOPDIR was here
/opt/boxen/rbenv/versions/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/rbconfig.rb:20: warning: already initialized constant RbConfig::CONFIG
/opt/rubies/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/rbconfig.rb:20: warning: previous definition of CONFIG was here
/opt/boxen/rbenv/versions/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/rbconfig.rb:270: warning: already initialized constant RbConfig::MAKEFILE_CONFIG
/opt/rubies/2.5.0/lib/ruby/2.5.0/x86_64-darwin17/rbconfig.rb:270: warning: previous definition of MAKEFILE_CONFIG was here
/opt/boxen/rbenv/versions/2.5.0/lib/ruby/2.5.0/digest.rb:6: warning: already initialized constant Digest::REQUIRE_MUTEX
/opt/rubies/2.5.0/lib/ruby/2.5.0/digest.rb:6: warning: previous definition of REQUIRE_MUTEX was here
rake aborted!
NameError: undefined method `extend_object' for class `Singleton'
Did you mean?  extended
/opt/boxen/rbenv/versions/2.5.0/lib/ruby/2.5.0/singleton.rb:151:in `undef_method'
/opt/boxen/rbenv/versions/2.5.0/lib/ruby/2.5.0/singleton.rb:151:in `singleton class'
/opt/boxen/rbenv/versions/2.5.0/lib/ruby/2.5.0/singleton.rb:131:in `<module:Singleton>'
/opt/boxen/rbenv/versions/2.5.0/lib/ruby/2.5.0/singleton.rb:96:in `<top (required)>'
/Users/viraptor/Projects/samson/config/application.rb:3:in `<top (required)>'
/Users/viraptor/Projects/samson/Rakefile:8:in `require_relative'
/Users/viraptor/Projects/samson/Rakefile:8:in `<top (required)>'
(See full trace by running task with --trace)
```

Disabling bootsnap options: `load_path_cache` and `autoload_paths_cache` fixes the issue.

Ruby: 2.5.0
Environment: MacOS 10.13

**Comment by MoacirPetry** [comment]
My solution around `Digest::REQUIRE_MUTEX` was to upgrade Ruby from `2.7.3` to `2.7.6`

I am using RVM and Rails `7.0.3`
