### ISSUE TITLE
ConvertMacrosToStages migration fails

### ISSUE THREAD

**Issue by viraptor** [zendesk/samson#2705]
The following migration failed with this error multiple times (maybe it was a failure per each macro?)

```
== 20170505201145 ConvertMacrosToStages: migrating ============================
unknown attribute 'no_reference_selection' for ConvertMacrosToStages::Stage.
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activemodel-5.1.4/lib/active_model/attribute_assignment.rb:48:in `_assign_attribute'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activemodel-5.1.4/lib/active_model/attribute_assignment.rb:40:in `block in _assign_attributes'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activemodel-5.1.4/lib/active_model/attribute_assignment.rb:39:in `each'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activemodel-5.1.4/lib/active_model/attribute_assignment.rb:39:in `_assign_attributes'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/attribute_assignment.rb:26:in `_assign_attributes'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activemodel-5.1.4/lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/core.rb:337:in `initialize'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/inheritance.rb:66:in `new'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/inheritance.rb:66:in `new'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/persistence.rb:50:in `create!'
/var/www/samson/tmp/build-152506568924693/db/migrate/20170505201145_convert_macros_to_stages.rb:22:in `block in up'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:63:in `block (2 levels) in find_each'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:63:in `each'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:63:in `block in find_each'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:129:in `block in find_in_batches'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:230:in `block in in_batches'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:214:in `loop'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:214:in `in_batches'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:128:in `find_in_batches'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/batches.rb:62:in `find_each'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/querying.rb:9:in `find_each'
/var/www/samson/tmp/build-152506568924693/db/migrate/20170505201145_convert_macros_to_stages.rb:20:in `up'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:795:in `exec_migration'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:776:in `block (2 levels) in migrate'
/usr/local/rbenv/versions/2.5.1/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:775:in `block in migrate'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:774:in `migrate'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:953:in `migrate'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1230:in `block in execute_migration_in_transaction'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `block in ddl_transaction'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `block in transaction'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/usr/local/rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/transactions.rb:210:in `transaction'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1298:in `ddl_transaction'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `each'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `block in migrate'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1148:in `migrate'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/local/rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/var/www/samson/shared/bundle/ruby/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/var/www/samson/tmp/build-152506568924693/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/var/www/samson/tmp/build-152506568924693/vendor/bundle/ruby/2.5.0/bin/rake:23:in `load'
/var/www/samson/tmp/build-152506568924693/vendor/bundle/ruby/2.5.0/bin/rake:23:in `<top (required)>'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/usr/local/rbenv/versions/2.5.1/bin/bundle:23:in `load'
/usr/local/rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
...
== 20170505201145 ConvertMacrosToStages: migrated (108.3071s) =================
```

Running on Ubuntu 14.04, ruby 2.5.1

**Comment by grosser** [comment]
should have been there since 20170402035231_add_macro_to_stages.rb
... and 20170505201145_convert_macros_to_stages.rb has it's own Stage class so that should have prevented any caching issues too.

can you check the logs to see if to 20170402035231_add_macro_to_stages.rb did not run ?

Otherwise we have a schema caching bug, should be easy to create two migrations that depend on each other to find out if a caching bug exists and if yes create a patch so that we reset all cached column information before each migration.

**Comment by viraptor** [comment]
Originally I migrated from v1323 which failed, but anything after commit 03d3b2df77b31e5f1299e4b7456c6ea6a099faf7 succeeds (bisected).

I'm not sure if this is something that can be retroactively fixed in master.

Test procedure:
```
git checkout (old_version)
mysql -u root -e 'drop database samson_test; create database samson_test;'
bundle install
CACHE_STORE=memory RAILS_ENV=test DATABASE_URL=mysql2://root@127.0.0.1/samson_test bundle exec rake db:migrate
git co db/schema.rb

git checkout master
bundle install
mysql -u root samson_test < add-macro.sql
CACHE_STORE=memory RAILS_ENV=test DATABASE_URL=mysql2://root@127.0.0.1/samson_test bundle exec rake db:migrate
```

With `add-macro.sql` being:
```
INSERT INTO `commands` (`command`, `created_at`, `updated_at`) VALUES ('do the thing', '2018-05-06 02:22:12', '2018-05-06 02:22:12');
INSERT INTO `projects` (`name`, `repository_url`, `created_at`, `updated_at`, `token`, `permalink`) VALUES ('foo', 'https://github.com/kelseyhightower/helloworld', '2018-05-06 02:24:29', '2018-05-06 02:24:29', '0750b1a16cc8c1389c247df4fabf0530', 'helloworld');
INSERT INTO `macros` (`name`, `reference`, `project_id`, `created_at`, `updated_at`) VALUES ('macro foo', 'bar', 1, '2018-05-06 02:25:43', '2018-05-06 02:25:43');
INSERT INTO `macro_commands` (`macro_id`, `command_id`, `position`, `created_at`, `updated_at`) VALUES (1, 1, 1, '2018-05-06 02:26:36', '2018-05-06 02:26:36');
```

**Comment by grosser** [comment]
dammit ... just confirmed this does indeed not work ... the schema is cached between different classes ... so we need to reset all schemas between migrations

**Comment by grosser** [comment]
```
class RemoveStuff < ActiveRecord::Migration[5.1]
  class Stage < ActiveRecord::Base
  end

  def change
    puts "RE #{Stage.columns_hash.keys}"
    remove_column :stages, :notify_email_address, :string
    puts "RE #{Stage.columns_hash.keys}"
  end
end


class TryStuff < ActiveRecord::Migration[5.1]
  class Stage < ActiveRecord::Base
  end

  def change
    puts "TR #{Stage.columns_hash.keys}"
  end
end

```

**Comment by grosser** [comment]
does https://github.com/zendesk/samson/pull/2749 fix it ?
