### ISSUE TITLE
Deleting stage fails (tries to delete nil)

### ISSUE THREAD

**Issue by viraptor** [zendesk/samson#2719]
On version v2236, deleting a stage fails with:
```
NoMethodError (undefined method `delete' for nil:NilClass):

app/models/stage.rb:241:in `block in destroy_stage_pipeline'
app/models/stage.rb:240:in `each'
app/models/stage.rb:240:in `destroy_stage_pipeline'
app/controllers/stages_controller.rb:75:in `destroy'
```
At https://github.com/zendesk/samson/blob/82f72d32a6904669ab761348b620e3cdfceeca67/app/models/stage.rb#L241 the next_stage_id is nil.

**Comment by viraptor** [comment]
This happens without the pipeline plugin, so `next_stage_ids` can be nil rather than `[]`.
