### ISSUE TITLE
Boot checker fails locally

### ISSUE THREAD

**Issue by cakejelly** [zendesk/samson#2779]
Hey, running into the following error when booting up samson. The output below is from `docker-compose up` but it also happens when running `bin/setup` locally. 

Any ideas?

```
Attaching to samson_samson_1
samson_1  | rake aborted!
samson_1  | Extra threads: [#<Thread:0x00005643c30f60b0@/usr/local/bundle/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:297 sleep>] should not be loaded
samson_1  | /app/lib/samson/boot_check.rb:24:in `check'
samson_1  | /app/config/application.rb:174:in `block in <class:Application>'
samson_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
samson_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
samson_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
samson_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
samson_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
samson_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `public_send'
samson_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `method_missing'
samson_1  | /app/config/environment.rb:6:in `<main>'
samson_1  | /usr/local/bundle/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
samson_1  | /usr/local/bundle/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
samson_1  | /usr/local/bundle/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
samson_1  | /usr/local/bundle/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
samson_1  | /usr/local/bundle/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
samson_1  | /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
samson_1  | /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
samson_1  | /usr/local/bundle/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
samson_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/application.rb:337:in `require_environment!'
samson_1  | /usr/local/bundle/gems/railties-5.2.0/lib/rails/application.rb:520:in `block in run_tasks_blocks'
samson_1  | /usr/local/bundle/gems/airbrake-7.3.0/lib/airbrake/rake.rb:19:in `execute'
samson_1  | /usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
samson_1  | Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config => environment
samson_1  | (See full trace by running task with --trace)
samson_samson_1 exited with code 1
```

**Comment by grosser** [comment]
thx for reporting!
(these errors are semi safe to ignore since they are just "sanity checks")

What happened is that it tries to ensure that no unnecessary threads are running.
I blocke the AR connection reaper before by setting `reaping_frequency: 0` (see https://github.com/zendesk/samson/pull/2718/files),
but that does  not work when a custom database config is used.

Connection reaping is not needed in development and I really like the idea of only having a single thread running, so I'll fix this up with a better patch!

**Comment by grosser** [comment]
done 🎉

**Comment by cakejelly** [comment]
@grosser thanks for the quick response and fix 👏 🙇
