### ISSUE TITLE
Unable to create commands using the API

### ISSUE THREAD

**Issue by danihodovic** [zendesk/samson#3149]
```
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
Completed 500 Internal Server Error in 28ms (ActiveRecord: 1.4ms)

NoMethodError (undefined method `permit' for "echo hello":String):

app/controllers/commands_controller.rb:89:in `command_params'
app/controllers/commands_controller.rb:127:in `project_from_params'
app/controllers/commands_controller.rb:109:in `authorize_custom_project_admin!'
```

The failing method seems to be:
```
  def command_params
    params.require(:command).permit(:command, :project_id)
  end
```

**Comment by danihodovic** [comment]
Thanks!
