### ISSUE TITLE
500 on project creation with bad URL

### ISSUE THREAD

**Issue by jamielennox** [zendesk/samson#3603]
Spinning this up in docker-compose for a look, i fat fingered the project URL and got the following 500: 

```
samson_1  | Completed 500 Internal Server Error in 446ms (ActiveRecord: 25.8ms)
samson_1  |
samson_1  |
samson_1  |
samson_1  | NoMethodError (undefined method `slice!' for nil:NilClass):
samson_1  |
samson_1  | app/models/project.rb:337:in `private_repository_url'
samson_1  | app/models/project.rb:315:in `valid_repository_url'
samson_1  | app/controllers/resource_controller.rb:37:in `block (2 levels) in create'
samson_1  | app/controllers/resource_controller.rb:35:in `create'
```

Seems like it'd be an easy fix.

**Comment by jamielennox** [comment]
Exact fat finger: `https:.//github.com/samson-test-org/example-project.git`

**Comment by grosser** [comment]
thx, yeah that's not a nice error to get :D
