### ISSUE TITLE
HTTP 500 on /deploys/confirm endpoint after clicking Review

### ISSUE THREAD

**Issue by alongwill** [zendesk/samson#3800]
We're attempting to upgrade samson from v2206 to v3167.

The database migrations have worked and the samson service starts. However deploys are not working. After clicking "Review"

In the Firefox developer tools the `/deploys/confirm` endpoint is showing a HTTP 500.

The samson logs show this error:
```
[5b9cf587-0434-47a2-9d9a-4927466e86fb]   Rendering deploys/changeset.html.erb
[5b9cf587-0434-47a2-9d9a-4927466e86fb] {:message=>"execute.terminal_executor.samson", :duration=>"1246.1ms", :script=>"cd /srv/samson/releases/v3167/cached_repos/906d2c70bd9e7088022925ce29d4b9e7..."}
[5b9cf587-0434-47a2-9d9a-4927466e86fb] {:message=>"execute.command_executor.samson", :duration=>"10.1ms", :script=>"git rev-parse master\\^\\{commit\\}"}
[5b9cf587-0434-47a2-9d9a-4927466e86fb]   Rendered changeset/_files.html.erb (Duration: 1260.8ms | Allocations: 1869)
[5b9cf587-0434-47a2-9d9a-4927466e86fb]   Rendered deploys/changeset.html.erb (Duration: 1261.9ms | Allocations: 2296)
[5b9cf587-0434-47a2-9d9a-4927466e86fb] Completed 500 Internal Server Error in 1286ms (ActiveRecord: 7.1ms | Allocations: 5995)
[5b9cf587-0434-47a2-9d9a-4927466e86fb]
[5b9cf587-0434-47a2-9d9a-4927466e86fb] ActionView::Template::Error (Changeset#error delegated to comparison.error, but comparison is nil: #<Changeset:0x0000000008b567d0 @project=#<Project id: 47, name: "user-service", repository_url: "git@github.com:********/user-service.git", deleted_at: nil, created_at: "2020-04-30 08:36:53", updated_at: "2020-06-01 10:23:57", token: [FILTERED], release_branch: "master", permalink: "user-service", description: "", owner: "test@********.com", include_new_deploy_groups: false, docker_release_branch: nil, release_source: "any", build_command_id: nil, dashboard: "", docker_image_building_disabled: false, dockerfiles: nil, build_with_gcb: false, show_gcr_vulnerabilities: false, kubernetes_allow_writing_to_root_filesystem: false, kubernetes_rollout_timeout: nil, kubernetes_namespace_id: nil, ignore_pending_checks: nil>, @repo="********/user-service", @reference="master", @previous_commit="94c4047010e5f233803acf04569aa39e005703d3", @comparison=nil>):
[5b9cf587-0434-47a2-9d9a-4927466e86fb]     1: <p>Commit range: <code><%= link_to changeset.commit_range, changeset.commit_range_url %></code></p>
[5b9cf587-0434-47a2-9d9a-4927466e86fb]     2: <% if changeset.error %>
[5b9cf587-0434-47a2-9d9a-4927466e86fb]     3:   <p class="alert alert-warning"><%= changeset.error %></p>
[5b9cf587-0434-47a2-9d9a-4927466e86fb]     4: <% end %>
[5b9cf587-0434-47a2-9d9a-4927466e86fb]     5:
[5b9cf587-0434-47a2-9d9a-4927466e86fb]
[5b9cf587-0434-47a2-9d9a-4927466e86fb] app/models/changeset.rb:7:in `rescue in error'
[5b9cf587-0434-47a2-9d9a-4927466e86fb] app/models/changeset.rb:7:in `error'
[5b9cf587-0434-47a2-9d9a-4927466e86fb] app/views/changeset/_files.html.erb:2
[5b9cf587-0434-47a2-9d9a-4927466e86fb] app/views/deploys/changeset.html.erb:5
[5b9cf587-0434-47a2-9d9a-4927466e86fb] app/views/deploys/changeset.html.erb:3:in `each'
[5b9cf587-0434-47a2-9d9a-4927466e86fb] app/views/deploys/changeset.html.erb:3
[5b9cf587-0434-47a2-9d9a-4927466e86fb] app/controllers/deploys_controller.rb:81:in `confirm'
[5b9cf587-0434-47a2-9d9a-4927466e86fb] app/controllers/concerns/wrap_in_with_deleted.rb:26:in `wrap_in_with_deleted
```

The commit range does not display:
![samson_deploy](https://user-images.githubusercontent.com/8058154/84281105-135f1600-ab30-11ea-928b-e59d85c1ffb4.png)

Can someone please advise what might be wrong?

**Comment by alongwill** [comment]
I updated `changeset.rb` with the following:
```ruby
  def find_comparison
    return NullComparison.new if empty?
    if @project.github?
      Rails.logger.info("github true")
    else
      Rails.logger.info("github false")
    end
```

The log file showed `github true` after clicking the review button.

I've had another look over the logs with `debug` enabled and can't see evidence of Github API requests failing. The Github API responses for calls like `/status`, `/check-suites`, `/check-runs` are all `200 OK`.

This is how the UI appears if that helps:
![samson_commit_range](https://user-images.githubusercontent.com/8058154/84356752-8d3ce100-abbc-11ea-870c-b8b153321f52.png)

**Comment by grosser** [comment]
sounds like all is good then ... if your comparison is always empty now we should take another look though
