### ISSUE TITLE
Deploy screen no longer showing git file differences after clicking Review

### ISSUE THREAD

**Issue by alongwill** [zendesk/samson#3901]
Since upgrading samson from `v2206 ` to `v3227` we are no longer seeing the filenames changed.

It just displays "There were no new file changes in this deploy."

![image](https://user-images.githubusercontent.com/8058154/102346118-44fce200-3f96-11eb-8cfd-246c691dde4f.png)

In the `/projects/user-service/stages/staging/deploys/confirm` `POST` request I noticed that only the new git reference is included. Should the current git reference also be included?
```
deploy[reference] | "47ed49d"
```

The full response payload is:
```
  <div class="tab-pane changeset-content" id="files">
    <p>Commit range: <code><a href="https://github.com/MyCorp/user-service/compare/fd67aae53db22adaf4fb2616b60ab34267e4e938...47ed49d">fd67aae53db22adaf4fb2616b60ab34267e4e938...47ed49d</a></code></p>

  <p>There were no new file changes in this deploy.</p>

  </div>
  <div class="tab-pane changeset-content" id="commits">
      <p>There were no new commits in this deploy.</p>

  </div>
  <div class="tab-pane changeset-content" id="pull_requests">
      <p>There were no pull requests in this deploy.</p>

  </div>
  <div class="tab-pane changeset-content" id="risks">
      <p>There were no pull requests in this deploy.</p>

  </div>
  <div class="tab-pane changeset-content" id="jira_issues">
      <p>No JIRA issues were referenced in this deploy.</p>

  </div>

<div class="tab-pane" id="environment-variables">
    No changes.
</div>
```

If there's any debugging I can do to help diagnose the issue please let me know.

Thank you

**Comment by grosser** [comment]
it should diff against the last successful release on that stage
what is that diff ? ... does it include changed files ?
can go into the controller and print what shas it is diffing ?

**Comment by m8051** [comment]
Hi @grosser, @alongwill , I recently installed the version 3313 and facing the same issue ...

<img width="1162" alt="Screenshot 2021-07-28 at 15 41 34" src="https://user-images.githubusercontent.com/2571020/127342865-14be848f-027b-4012-8742-ef4158fb9cae.png">

<img width="1166" alt="Screenshot 2021-07-28 at 15 41 38" src="https://user-images.githubusercontent.com/2571020/127342872-42946a3f-2e54-4f08-b446-455c469f8ab3.png">

<img width="1176" alt="Screenshot 2021-07-28 at 15 41 44" src="https://user-images.githubusercontent.com/2571020/127342876-bafe4ef7-938a-4fdd-b5eb-f62eef833b0f.png">

Did you figure it out?

Thanks.

**Comment by grosser** [comment]
try running it locally and then print what it thinks the diff is to debug
further, I did not run into this so far, so I'm thinking it's an edge-case

**Comment by m8051** [comment]
thanks @grosser, I downgraded Samson to an older version and spotted these in the logs:

```bash
Completed 200 OK in 45ms (Views: 31.8ms | ActiveRecord: 7.0ms | Allocations: 17393)
Finished "/cable/" [WebSocket] for 81.173.14.14 at 2021-07-28 20:33:07 +0000
DeployNotificationsChannel stopped streaming from deploy_notifications
Started GET "/projects/membership/deploys/4554/changeset" for 81.173.14.14 at 2021-07-28 20:33:07 +0000
Processing by DeploysController#changeset as HTML
  Parameters: {"project_id"=>"membership", "id"=>"4554"}
  Rendering deploys/changeset.html.erb
  Rendered changeset/_files.html.erb (Duration: 2.9ms | Allocations: 813)
  Rendered deploys/changeset.html.erb (Duration: 3.3ms | Allocations: 873)
Completed 500 Internal Server Error in 20ms (ActiveRecord: 4.0ms | Allocations: 3923)

ActionView::Template::Error (Changeset#error delegated to comparison.error, but comparison is nil: #<Changeset:0x0000561049142e18 @project=#<Project id: 26, name: "membership", repository_url: "https://github.com/xxxxx/membership.git", deleted_at: nil, created_at: "2019-07-17 09:43:24", updated_at: "2021-07-23 10:13:56", token: [FILTERED], release_branch: "", permalink: "membership", description: "The Membership Application", owner: "xxx@xxxx", include_new_deploy_groups: false, docker_release_branch: nil, release_source: "none", build_command_id: nil, dashboard: "", docker_image_building_disabled: false, dockerfiles: nil, build_with_gcb: false, show_gcr_vulnerabilities: false, kubernetes_allow_writing_to_root_filesystem: false, jenkins_status_checker: false, use_env_repo: false, kubernetes_rollout_timeout: nil, kubernetes_namespace_id: nil, jira_issue_prefix: nil, ignore_pending_checks: nil>, @repo="xxxxxx/membership", @reference="f9231530913058f20a93d5c5714c0389b22c25b1", @previous_commit="9be4dcbc6f8eb0bfd4ecb08c819b1a3d51385428", @comparison=nil>):
    1: <p>Commit range: <code><%= link_to changeset.commit_range, changeset.commit_range_url %></code></p>
    2: <% if changeset.error %>
    3:   <p class="alert alert-warning"><%= changeset.error %></p>
    4: <% end %>
    5:

app/models/changeset.rb:7:in `rescue in error'
app/models/changeset.rb:7:in `error'
app/views/changeset/_files.html.erb:2
app/views/deploys/changeset.html.erb:5
app/views/deploys/changeset.html.erb:3:in `each'
app/views/deploys/changeset.html.erb:3
app/controllers/deploys_controller.rb:108:in `changeset'
app/controllers/concerns/wrap_in_with_deleted.rb:26:in `wrap_in_with_deleted'
Started GET "/cable" for 81.173.14.14 at 2021-07-28 20:33:12 +0000
Started GET "/cable/" [WebSocket] for 81.173.14.14 at 2021-07-28 20:33:12 +0000
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Registered connection (xxxxxxxxxxxxxxx)
DeployNotificationsChannel is transmitting the subscription confirmation
DeployNotificationsChannel is streaming from deploy_notifications
```

I use Memcached locally as well and after rebooting the server, things got back to normal and it seems everything is working fine now ... Not sure what the issue was tbh, maybe something was not correctly stored in cache ...

**Comment by grosser** [comment]
yeah, the comparisson object got new things added to it.
Ideally we'd throw away all caches when changing the version :/
