### ISSUE TITLE
Assets not loading

### ISSUE THREAD

**Issue by dopesong** [zendesk/samson#721]
All assets returning: 

```
Puma caught this error: No route matches [GET] "/stylesheets/application.css" (ActionController::RoutingError)
/home/samson/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:38:in `call_app'
/home/samson/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `block in call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/samson/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/samson/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `tagged'
/home/samson/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.5/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/static.rb:116:in `call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/engine.rb:518:in `call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/railties-4.2.5/lib/rails/application.rb:165:in `call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/commonlogger.rb:31:in `call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/configuration.rb:79:in `call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:541:in `handle_request'
/home/samson/vendor/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:388:in `process_client'
/home/samson/vendor/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/server.rb:270:in `block in run'
/home/samson/vendor/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `call'
/home/samson/vendor/bundle/ruby/2.1.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by steved** [comment]
If you're running it in a production environment, make sure the assets are precompiled as samson is not [configured](https://github.com/zendesk/samson/blob/master/config/environments/production.rb#L23) to serve them.

**Comment by dopesong** [comment]
```Puma 2.15.3 starting...
* Min threads: 0, max threads: 16
* Environment: test```

**Comment by steved** [comment]
Static assets also aren't [configured](https://github.com/zendesk/samson/blob/master/config/environments/test.rb#L17) for the test environment, though I wouldn't recommend running the server in it since [jobs also won't run](https://github.com/zendesk/samson/blob/master/config/environments/test.rb#L41).

**Comment by jurgenweber** [comment]
for those that do not know the inner works of ruby/rails here is how you do this:

RUN RAILS_ENV=production bundle exec rake assets:precompile
