### ISSUE TITLE
Error using bundler and RVM

### ISSUE THREAD

**Issue by michael-bouvy** [zendesk/samson#900]
Hi,

I am currently using release 6282e44f of Samson, with **Ruby 2.2.3** installed via RVM under a Samson user.

I installed Samson dependencies with a `bundle install`, and I run Samson with the following command:

```
bundle exec puma -C ./config/puma.rb -e production
```

To deploy a project with Capistrano 3, I've defined the following commands:

```
bundle install
bundle exec cap ${STAGE} deploy
```

However, the process hangs at the first command:

```
» bundle install
/home/samson/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 14 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/samson/.gem/ruby/2.2.0:/home/samson/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0', execute `gem env` for more information
	from /home/samson/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /home/samson/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /home/samson/.rvm/gems/ruby-2.2.3/bin/bundle:22:in `<main>'
	from /home/samson/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/samson/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

I tried to remove completely Ruby 2.2.3 + the gems + RVM and to reinstall everything, but I still got the same error message.

As a (temporary, I hope) workaround, I added the following command to update environment variables:

```
. $(rvm 2.2.3 do rvm env --path)
```

**Am I missing something?**

Samson is installed under `/opt/samson`.

Some debug output that may be useful:

```
samson@samson:~$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
```

```
samson@samson:~$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/samson/.rvm/gems/ruby-2.2.3
  - RUBY EXECUTABLE: /home/samson/.rvm/rubies/ruby-2.2.3/bin/ruby
  - EXECUTABLE DIRECTORY: /home/samson/.rvm/gems/ruby-2.2.3/bin
  - SPEC CACHE DIRECTORY: /home/samson/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/samson/.rvm/rubies/ruby-2.2.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/samson/.rvm/gems/ruby-2.2.3
     - /home/samson/.rvm/gems/ruby-2.2.3@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/samson/.rvm/gems/ruby-2.2.3/bin
     - /home/samson/.rvm/gems/ruby-2.2.3@global/bin
     - /home/samson/.rvm/rubies/ruby-2.2.3/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/local/games
     - /usr/games
     - /home/samson/.rvm/bin
     - /home/samson/.rvm/bin
```

**Comment by henders** [comment]
A silly question, but have you installed bundler in that version of ruby?
``` gem install bundler```

And if so, what does ```gem list``` show?

**Comment by michael-bouvy** [comment]
When logged in into a shell with samson user, `gem list` shows dozens of gems, including bundler:

```
*** LOCAL GEMS ***

...
bundler (1.11.2)
...
```

However, when running this command within a Samson deployment, I get the following:

```
» ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

» gem list
bigdecimal (1.2.6)
bundler-unload (1.0.2)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
io-console (0.4.3)
json (1.8.1)
minitest (5.4.3)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
test-unit (3.0.8)

» gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/samson/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0
  - RUBY EXECUTABLE: /home/samson/.rvm/rubies/ruby-2.2.3/bin/ruby
  - EXECUTABLE DIRECTORY: /home/samson/.rvm/rubies/ruby-2.2.3/bin
  - SPEC CACHE DIRECTORY: /home/samson/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/samson/.rvm/rubies/ruby-2.2.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/samson/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0
     - /home/samson/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/samson/.rvm/gems/ruby-2.2.3/bin
     - /home/samson/.rvm/gems/ruby-2.2.3@global/bin
     - /home/samson/.rvm/rubies/ruby-2.2.3/bin
     - /home/samson/.rvm/bin
     - /usr/local/rvm/gems/ruby-2.2.3/bin
     - /usr/local/rvm/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/local/games
     - /usr/games
```

**Comment by henders** [comment]
Assuming you are using rbenv to manage your ruby versions...
```
$ cd /opt/samson
$ gem install bundler
```

This should pickup the .ruby-version file from within /opt/samson and switch to the proper ruby version that Samson will use. I think when you just switched to the samson user, rbenv was using a different default version of ruby, and thus led to false positive of seeing bundler installed.

**Comment by michael-bouvy** [comment]
Mmhhh I'm actually using RVM, maybe should I switch to rbenv? Do you think this could make a difference?

**Comment by henders** [comment]
Nope, just do the above anyway.... RVM should respect that .ruby-version as well

**Comment by michael-bouvy** [comment]
```
samson@samson:/opt/samson$ gem install bundler
Successfully installed bundler-1.11.2
Parsing documentation for bundler-1.11.2
Done installing documentation for bundler after 2 seconds
1 gem installed
```

I one got an error using RVM about a missing `GEM_PATH` env variable ... maybe is my Samson install using the proper Ruby version but looking at the wrong place for gems ?

**Comment by henders** [comment]
Not sure about that error (haven't used RVM in years), but if you retry that ```bundle install``` and the other steps to startup Samson, does it now work?

**Comment by michael-bouvy** [comment]
Still the same ...

BUT, I realized that the `GEM_PATH` is not the same wether running from the shell or from Samson:

```
  - GEM PATHS:
     - /home/samson/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0
     - /home/samson/.gem/ruby/2.2.0
```

Instead of (from the shell):

```
  - GEM PATHS:
     - /home/samson/.rvm/gems/ruby-2.2.3@2.2.3
     - /home/samson/.rvm/gems/ruby-2.2.3@global
```

**Comment by henders** [comment]
Ah, is there a .ruby-version in the project's git repo that you are trying
to deploy?

**Comment by michael-bouvy** [comment]
No.

*Michael BOUVY*
+33.6.26.25.50.32

2016-04-28 17:44 GMT+02:00 Shane Hender <notifications@github.com>:

> Ah, is there a .ruby-version in the project's git repo that you are trying
> to deploy?

**Comment by michael-bouvy** [comment]
I just tried with **rbenv**, everything works fine, although gem paths are the same as with RVM...

But now gem paths are identical wether ran from bash shell or by Samson.

Anyway, thanks a lot for your help @henders!
